# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ase-infra-test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://jstack.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4767e0f97d5947cf9c237e5a88114eea }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b6d2d617a1a744b2a97710e48ff259a8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_4767e0f97d5947cf9c237e5a88114eea }}/demo/azure-app-service-demo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ase-infra-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7d46c9cd5d364a0a8d7ed58294ff1199 }}
        images: 'jstack.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4767e0f97d5947cf9c237e5a88114eea }}/demo/azure-app-service-demo:${{ github.sha }}'